#!/bin/bash
echo "Old .dotfiles moved to .file.old";

INSTALLDIR=${1:-$HOME}

#for i in .bash  .bash_logout  .bashrc  bin  completion 
for i in .vimperatorrc .tmux.conf .tmux-powerlinerc
do
	mv $INSTALLDIR/$i $INSTALLDIR/$i.old 2> /dev/null
	ln -s $PWD/$i $INSTALLDIR/$i;
done;

echo -n "Do you want to use my vim configs? [n/Y]"
read -n 1 use_vim_configs

if [ "$use_vim_configs" == "Y" ]; then
    if [ ! -d $INSTALLDIR/.node-completion ]; then
        ln -s $PWD/.vim $INSTALLDIR/.vim
    fi
	mv $INSTALLDIR/.vimrc $INSTALLDIR/.vimrc.old 2> /dev/null
	ln -s $PWD/.vimrc $INSTALLDIR/.vimrc
fi
echo


if [ ! -d $INSTALLDIR/.node-completion ]; then
	mkdir $INSTALLDIR/.node-completion
fi

if [ ! -d $HOME/linux_repos ]; then
	mkdir $HOME/linux_repos
fi

if [ ! -d $HOME/linux_repos/tmux-powerline ]; then
	git clone git://github.com/erikw/tmux-powerline.git $HOME/linux_repos/tmux-powerline
fi

echo "Initializing submodules..."
git submodule init && git submodule update
